approvedGitRepositories:
  - "**"

enableScripts: true

httpTimeout: 300000
httpRetry: 5

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@oxc-resolver/binding-wasm32-wasi@*":
    dependencies:
      "@emnapi/core": "npm:^1.7.1"
      "@emnapi/runtime": "npm:^1.7.1"
